# Generated by Django 6.0.3 on 2026-04-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='status',
            field=models.CharField(default='enviada', max_length=20),
        ),
    ]
